language: go

sudo: required
services:
  - docker

go:
  - 1.10.x

notifications:
  email: false

before_script:
  - go get -t -v
  - chmod +x bin/docker_push.sh

script:
  - go test

after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
